package com.yichen.community.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.question_id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_status
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private Byte categoryStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.question_id
     *
     * @return the value of category.question_id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.question_id
     *
     * @param questionId the value for category.question_id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_status
     *
     * @return the value of category.category_status
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public Byte getCategoryStatus() {
        return categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_status
     *
     * @param categoryStatus the value for category.category_status
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setCategoryStatus(Byte categoryStatus) {
        this.categoryStatus = categoryStatus;
    }
}