package com.yichen.community.model;

public class UserDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.gender
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.industry
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.profession
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.signature
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.background_image
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    private String backgroundImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.id
     *
     * @return the value of user_detail.id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.id
     *
     * @param id the value for user_detail.id
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.gender
     *
     * @return the value of user_detail.gender
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.gender
     *
     * @param gender the value for user_detail.gender
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.industry
     *
     * @return the value of user_detail.industry
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.industry
     *
     * @param industry the value for user_detail.industry
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.profession
     *
     * @return the value of user_detail.profession
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.profession
     *
     * @param profession the value for user_detail.profession
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.signature
     *
     * @return the value of user_detail.signature
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.signature
     *
     * @param signature the value for user_detail.signature
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.background_image
     *
     * @return the value of user_detail.background_image
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public String getBackgroundImage() {
        return backgroundImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.background_image
     *
     * @param backgroundImage the value for user_detail.background_image
     *
     * @mbg.generated Mon Jan 20 11:37:03 CST 2020
     */
    public void setBackgroundImage(String backgroundImage) {
        this.backgroundImage = backgroundImage == null ? null : backgroundImage.trim();
    }
}